version: '3.9'

volumes:
  certs: {}

networks:
  default:
    external:
      name: rsyslogd


services: 
 rsyslogclt:
    build:
      context: .
      dockerfile: Dockerfile
    image: relp-rsyslog:client # adds tagging
    container_name: rsyslogclt
    hostname: rsyslogclt
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - RSYSLOGSRV_CENTRAL=""
      - RSYSLOGSRV_SECONDARY=""
    volumes:
      - ./PATH_TO_CA_CERT:/rsyslog-certs:ro
